spring:
  datasource:
    name: dbsource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.108.130:3306/db_zh_bicycle?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123321
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validationQuery: SELECT 1
      initialSize: 30
      maxActive: 35
      minIdle: 0
      maxWait: 60000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      removeAbandoned: true
      removeAbandonedTimeout: 300
      logAbandoned: false
      
mybatis:
  mapper-locations:
    - classpath:com/zh/manager/business/dao/**/*.xml