spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
            
custom: 
  quartzCron: "*/2 * * * * ?"
  quartzCron_alarm: "*/2 * * * * ?"
  jobGroupName: jobGroupName
  triggerGroupName: triggerGroupName
  websocketJobName: websocket
  websocketTriggerName: websocket
  