spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true